[theme]
primaryColor = "#3498db"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#000000"
font = "sans serif"
base = "light"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true
headless = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
caching = true
displayEnabled = true
showErrorDetails = false